POST http://localhost:3003/criarturma
Content-Type: application/json

{
    "nome": "Teste8",
    "inicio": "16/10/2021",
    "final": "25/04/2022",
    "modulo": "0"
}

###
POST http://localhost:3003/cadastroaluno
Content-Type: application/json

{
    "nome": "aluno6",
    "email": "aluno6@aluno6.com",
    "dataNasc": "03/12/1997"
}

###

POST http://localhost:3003/cadastrodocente
Content-Type: application/json

{
    "nome": "Professor 1",
    "email": "professor1@professor1.com",
    "dataNasc": "03/02/1990",
    "turmaId": 1617216361
}

###
POST http://localhost:3003/cadastropassatempo
Content-Type: application/json

{
    "nome": "Assistir filmes"
}

###
POST http://localhost:3003/cadastroespecialidade
Content-Type: application/json

{
    "nome": "Back-end"
}

###

PUT http://localhost:3003/adicionaraluno
Content-Type: application/json

{
    "estudanteId":,
    "turmaId": 1617215410 
}

###
GET http://localhost:3003/buscaridadealuno/1617220251