POST http://localhost:3003/criarturma
Content-Type: application/json

{
    "nome": "Teste6",
    "inicio": "16/10/2021",
    "final": "25/04/2022",
    "modulo": "f"
}

###
POST http://localhost:3003/cadastroaluno
Content-Type: application/json

{
    "nome": "Teste 5",
    "email": "teste5@teste5.com",
    "dataNasc": "03/02/1990",
    "turmaId": 1617216361
}

###

POST http://localhost:3003/cadastrodocente
Content-Type: application/json

{
    "nome": "Professor 1",
    "email": "professor1@professor1.com",
    "dataNasc": "03/02/1990",
    "turmaId": 1617216361
}

###
POST http://localhost:3003/cadastropassatempo
Content-Type: application/json

{
    "nome": "Leitura."
}

###
POST http://localhost:3003/cadastroespecialidade
Content-Type: application/json

{
    "nome": "Back-end"
}